---
title: "Quality Control"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(patchwork)
```

```{r}
abundance_1 <- read_csv("results/data/prepared/raw_abundance.csv")
groups_1 <- read_csv("results/data/prepared/groups.csv")
plates_1 <- read_csv("data/cohort_GD1/plates.csv")

data_1 <- abundance_1 %>% 
  pivot_longer(-sample, names_to = "glycan", values_to = "area") %>% 
  left_join(groups_1, by = "sample") %>% 
  filter(group == "QC") %>%
  select(-group) %>% 
  left_join(plates_1 %>% select(sample, plate), by = "sample") %>% 
  select(plate, sample, glycan, area)

data_1 <- data_1 %>% 
  pivot_wider(id_cols = glycan, names_from = sample, values_from = area) %>% 
  mutate(S529 = (S536 + S573) / 2, S745 = (S683 + S721) / 2) %>% 
  pivot_longer(-glycan, names_to = "sample", values_to = "area") %>%
  left_join(data_1 %>% distinct(sample, plate), by = "sample") %>% 
  select(plate, sample, glycan, area)

convert_glycan <- function(comp) {
  comp = str_replace(comp, "\\[.*?\\]", "")
  comp = str_replace(comp, "Hex\\((\\d+)\\)", "H\\1")
  comp = str_replace(comp, "HexNAc\\((\\d+)\\)", "N\\1")
  comp = str_replace(comp, "dHex\\((\\d+)\\)", "F\\1")
  comp = str_replace(comp, "NeuAc\\((\\d+)\\)", "S\\1")
  return(comp)
}

abundance_2 <- read_csv("results/data/glyhunter_results_GD2/summary_area.csv")
groups_2 <- read_csv("data/cohort_GD2/maldi_pos_and_group.csv")

data_2 <- abundance_2 %>% 
  mutate(glycan = convert_glycan(glycan)) %>% 
  pivot_longer(-glycan, names_to = "sample", values_to = "area") %>% 
  mutate(maldi_pos = str_split_i(sample, "_", 3), .keep = "unused") %>%
  left_join(groups_2, by = "maldi_pos") %>% 
  filter(group == "QC") %>% 
  mutate(plate = if_else(str_starts(maldi_pos, "D"), 9, 10)) %>% 
  select(plate, sample, glycan, area)

abundance_3 <- read_csv("results/data/glyhunter_results_SH/summary_area.csv")
groups_3 <- read_csv("data/cohort_SH/maldi_pos_and_group.csv")

data_3 <- abundance_3 %>% 
  mutate(glycan = convert_glycan(glycan)) %>% 
  pivot_longer(-glycan, names_to = "sample", values_to = "area") %>% 
  mutate(maldi_pos = str_split_i(sample, "_", 3), .keep = "unused") %>%
  left_join(groups_3, by = "maldi_pos") %>% 
  filter(group == "QC") %>% 
  mutate(plate = if_else(maldi_pos %in% c("D1", "D2", "D3"), 11, 12)) %>% 
  select(plate, sample, glycan, area)

data <- bind_rows(list(
  GD1 = data_1,
  GD2 = data_2,
  XZ  = data_3
), .id = "cohort") %>% 
  complete(nesting(cohort, plate, sample), glycan, fill = list(area = NA)) %>% 
  mutate(abundance = area / sum(area, na.rm = TRUE) * 100, .by = sample, .keep = "unused")

rm(data_1, data_2, data_3)
rm(abundance_1, groups_1, plates_1, abundance_2, groups_2, abundance_3, groups_3)
```

```{r}
top_30_glycans <- data %>% 
  summarise(mean_abundance = mean(abundance, na.rm = TRUE), .by = glycan) %>% 
  slice_max(mean_abundance, n = 30) %>% 
  pull(glycan)

top_30_data <- data %>% 
  filter(glycan %in% top_30_glycans) %>% 
  mutate(abundance = abundance / sum(abundance, na.rm = TRUE) * 100, .by = sample)
```

```{r}
qc_cv <- top_30_data %>% 
  summarise(cv = sd(abundance, na.rm = TRUE) / mean(abundance, na.rm = TRUE), .by = c(plate, cohort, glycan))
```

```{r}
qc_cv %>% 
  summarise(median_cv = median(cv, na.rm = TRUE), .by = cohort)
```

```{r}
ggplot(qc_cv, aes(x = cv, fill = cohort)) +
  geom_density(alpha = 0.5) +
  labs(x = "Coefficient of Variation", y = "Density") +
  guides(fill = guide_legend(title = "Cohort", position = "inside")) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.02)), limits = c(0, 1)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.02))) +
  theme_classic() +
  theme(
    legend.position.inside = c(0.7, 0.5)
  )
ggsave("results/figures/data_quality/QC_CV_density.pdf", width = 3, height = 3)
tgutil::ggpreview(width = 3, height = 3)
```

```{r}
qc_cor_mat <- top_30_data %>% 
  select(sample, glycan, abundance) %>% 
  pivot_wider(names_from = sample, values_from = abundance) %>% 
  column_to_rownames("glycan") %>%
  log2() %>% 
  cor(use = "complete.obs")
qc_cor <- qc_cor_mat %>% 
  as.data.frame() %>% 
  rownames_to_column("sample1") %>% 
  pivot_longer(-sample1, names_to = "sample2", values_to = "r") %>% 
  mutate(
    sample1_no = as.integer(str_sub(sample1, start = 2)),
    sample2_no = as.integer(str_sub(sample2, start = 2))
  ) %>% 
  filter(sample1_no > sample2_no)
```

```{r}
median(qc_cor$r, na.rm = TRUE)
```

```{r}
temp <- qc_cor %>% 
  left_join(data %>% distinct(sample, plate, cohort), by = c("sample1" = "sample")) %>% 
  rename(plate1 = plate, cohort1 = cohort) %>%
  left_join(data %>% distinct(sample, plate, cohort), by = c("sample2" = "sample")) %>%
  rename(plate2 = plate, cohort2 = cohort)
inter_plate_qc_cor <- temp %>% 
  filter(plate1 != plate2)
intra_plate_qc_cor <- temp %>% 
  filter(plate1 == plate2)
inter_cohort_qc_cor <- temp %>% 
  filter(cohort1 != cohort2)
intra_cohort_qc_cor <- temp %>% 
  filter(cohort1 == cohort2)
rm(temp)
```

```{r}
cli::cat_line(median(inter_plate_qc_cor$r))
cli::cat_line(median(intra_plate_qc_cor$r))
cli::cat_line(median(inter_cohort_qc_cor$r))
cli::cat_line(median(intra_cohort_qc_cor$r))
```

```{r}
# Should be run in console
pdf("results/figures/data_quality/QC_corrplot.pdf", width = 8, height = 8)
corrplot::corrplot(
  qc_cor_mat,
  method = "ellipse",
  type = "upper",
  tl.pos = "lt",
  tl.cex = 0.6,
  tl.col = "black",
  col = corrplot::COL1("Oranges"),
  col.lim = c(0, 1)
)
corrplot::corrplot(
  qc_cor_mat,
  add = TRUE,
  method = "color",
  type = "lower",
  tl.pos = "n",
  addCoef.col = "white",
  addgrid.col = "white",
  number.cex = 0.4,
  number.digits = 2,
  col = corrplot::COL1("Oranges"),
  col.lim = c(0, 1)
)
dev.off()
```

```{r}
plate_cor_boxplot <- bind_rows(list(
  `inter-plate` = inter_plate_qc_cor %>% select(sample1, sample2, r),
  `intra-plate` = intra_plate_qc_cor %>% select(sample1, sample2, r)
), .id = "type") %>% 
  ggplot(aes(type, r)) +
  geom_boxplot(aes(color = type), outlier.alpha = 0) +
  geom_jitter(aes(color = type), width = 0.2, alpha = 0.5) +
  guides(fill = "none", color = "none") +
  labs(x = NULL, y = "Pearson's r") +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
  )

cohort_cor_boxplot <- bind_rows(list(
  `inter-cohort` = inter_cohort_qc_cor %>% select(sample1, sample2, r),
  `intra-cohort` = intra_cohort_qc_cor %>% select(sample1, sample2, r)
), .id = "type") %>% 
  ggplot(aes(type, r)) +
  geom_boxplot(aes(color = type), outlier.alpha = 0) +
  geom_jitter(aes(color = type), width = 0.2, alpha = 0.5) +
  guides(fill = "none", color = "none") +
  labs(x = NULL, y = "Pearson's r") +
  theme_bw() +
  theme(
    panel.grid = element_blank(),
  )

cor_boxplots <- plate_cor_boxplot + cohort_cor_boxplot + plot_layout(nrow = 1)
ggsave("results/figures/data_quality/QC_cor_boxplots.pdf", cor_boxplots, width = 5, height = 3)
tgutil::ggpreview(cor_boxplots, width = 5, height = 3)
```
